import pygame as p

TILE_TYPES = {
	"grass": [[p.K_l, p.K_1], 0, True],
	"water": [[p.K_l, p.K_2], 20, True],

	"path-stone": [[p.K_p, p.K_1], 22, True],
	"path-brick": [[p.K_p, p.K_2], 22, True],

	"road-street-": [[p.K_r, p.K_1], 35, True],
	# "road-dual-": [[p.K_r, p.K_1], 35, True],

	"redflowers": [[p.K_k, p.K_1], 15, True],

	"zone-mixed-low": [[p.K_z, p.K_2], 30, True],
	"zone-mixed-mid": [[p.K_z, p.K_3], 110, True],
	"zone-mixed-high": [[p.K_z, p.K_4], 250, True],

	"zone-res-low": [[p.K_x, p.K_2], 23, True],
	"zone-res-mid": [[p.K_x, p.K_3], 92, True],
	"zone-res-high": [[p.K_x, p.K_4], 230, True],

	"zone-com-low": [[p.K_c, p.K_2], 27, True],
	"zone-com-mid": [[p.K_c, p.K_3], 100, True],
	"zone-com-high": [[p.K_c, p.K_4], 240, True],

	"zone-ind-low": [[p.K_v, p.K_2], 23, True],
	"zone-ind-mid": [[p.K_v, p.K_3], 92, True],
	"zone-ind-high": [[p.K_v, p.K_4], 230, True],
}

BUILDINGS_LIST = {
	"road-street-n":    [False, TILE_TYPES["road-street-"][1]],
	"road-street-s":    [False, TILE_TYPES["road-street-"][1]],
	"road-street-w":    [False, TILE_TYPES["road-street-"][1]],
	"road-street-e":    [False, TILE_TYPES["road-street-"][1]],
	"road-street-ns":   [False, TILE_TYPES["road-street-"][1]],
	"road-street-nw":   [False, TILE_TYPES["road-street-"][1]],
	"road-street-ne":   [False, TILE_TYPES["road-street-"][1]],
	"road-street-sw":   [False, TILE_TYPES["road-street-"][1]],
	"road-street-se":   [False, TILE_TYPES["road-street-"][1]],
	"road-street-swe":  [False, TILE_TYPES["road-street-"][1]],
	"road-street-we":   [False, TILE_TYPES["road-street-"][1]],
	"road-street-nsw":  [False, TILE_TYPES["road-street-"][1]],
	"road-street-nse":  [False, TILE_TYPES["road-street-"][1]],
	"road-street-nwe":  [False, TILE_TYPES["road-street-"][1]],
	"road-street-nswe": [False, TILE_TYPES["road-street-"][1]],

	# "road-dual-n":    [False, TILE_TYPES["road-dual-"][1]],
	# "road-dual-s":    [False, TILE_TYPES["road-dual-"][1]],
	# "road-dual-w":    [False, TILE_TYPES["road-dual-"][1]],
	# "road-dual-e":    [False, TILE_TYPES["road-dual-"][1]],
	# "road-dual-ns":   [False, TILE_TYPES["road-dual-"][1]],
	# "road-dual-nw":   [False, TILE_TYPES["road-dual-"][1]],
	# "road-dual-ne":   [False, TILE_TYPES["road-dual-"][1]],
	# "road-dual-sw":   [False, TILE_TYPES["road-dual-"][1]],
	# "road-dual-se":   [False, TILE_TYPES["road-dual-"][1]],
	# "road-dual-swe":  [False, TILE_TYPES["road-dual-"][1]],
	# "road-dual-we":   [False, TILE_TYPES["road-dual-"][1]],
	# "road-dual-nsw":  [False, TILE_TYPES["road-dual-"][1]],
	# "road-dual-nse":  [False, TILE_TYPES["road-dual-"][1]],
	# "road-dual-nwe":  [False, TILE_TYPES["road-dual-"][1]],
	# "road-dual-nswe": [False, TILE_TYPES["road-dual-"][1]],

	"mixed-low": [False, TILE_TYPES["zone-mixed-low"][1]*1],
	"mixed-mid": [False, TILE_TYPES["zone-mixed-mid"][1]*1],
	"mixed-high": [False, TILE_TYPES["zone-mixed-high"][1]*1],
	"res-low": [False, TILE_TYPES["zone-res-low"][1]*1],
	"res-mid": [False, TILE_TYPES["zone-res-mid"][1]*1],
	"res-high": [False, TILE_TYPES["zone-res-high"][1]*1],
	"com-low": [False, TILE_TYPES["zone-com-low"][1]*1],
	"com-mid": [False, TILE_TYPES["zone-com-mid"][1]*1],
	"com-high": [False, TILE_TYPES["zone-com-high"][1]*1],
	"ind-low": [False, TILE_TYPES["zone-ind-low"][1]*1],
	"ind-mid": [False, TILE_TYPES["zone-ind-mid"][1]*1],
	"ind-high": [False, TILE_TYPES["zone-ind-high"][1]*1],

	"1-mixed-low": [False, TILE_TYPES["zone-mixed-low"][1]*1],
	"1-mixed-mid": [False, TILE_TYPES["zone-mixed-mid"][1]*1],
	"1-mixed-high": [False, TILE_TYPES["zone-mixed-high"][1]*1],
	"1-res-low": [False, TILE_TYPES["zone-res-low"][1]*1],
	"1-res-mid": [False, TILE_TYPES["zone-res-mid"][1]*1],
	"1-res-high": [False, TILE_TYPES["zone-res-high"][1]*1],
	"1-com-low": [False, TILE_TYPES["zone-com-low"][1]*1],
	"1-com-mid": [False, TILE_TYPES["zone-com-mid"][1]*1],
	"1-com-high": [False, TILE_TYPES["zone-com-high"][1]*1],
	"1-ind-low": [False, TILE_TYPES["zone-ind-low"][1]*1],
	"1-ind-mid": [False, TILE_TYPES["zone-ind-mid"][1]*1],
	"1-ind-high": [False, TILE_TYPES["zone-ind-high"][1]*1],

	"2-mixed-low": [False, TILE_TYPES["zone-mixed-low"][1]*4],
	"2-mixed-mid": [False, TILE_TYPES["zone-mixed-mid"][1]*4],
	"2-mixed-high": [False, TILE_TYPES["zone-mixed-high"][1]*4],
	"2-res-low": [False, TILE_TYPES["zone-res-low"][1]*4],
	"2-res-mid": [False, TILE_TYPES["zone-res-mid"][1]*4],
	"2-res-high": [False, TILE_TYPES["zone-res-high"][1]*4],
	"2-com-low": [False, TILE_TYPES["zone-com-low"][1]*4],
	"2-com-mid": [False, TILE_TYPES["zone-com-mid"][1]*4],
	"2-com-high": [False, TILE_TYPES["zone-com-high"][1]*4],
	"2-ind-low": [False, TILE_TYPES["zone-ind-low"][1]*4],
	"2-ind-mid": [False, TILE_TYPES["zone-ind-mid"][1]*4],
	"2-ind-high": [False, TILE_TYPES["zone-ind-high"][1]*4],

	"3-mixed-low": [False, TILE_TYPES["zone-mixed-low"][1]*9],
	"3-mixed-mid": [False, TILE_TYPES["zone-mixed-mid"][1]*9],
	"3-mixed-high": [False, TILE_TYPES["zone-mixed-high"][1]*9],
	"3-res-low": [False, TILE_TYPES["zone-res-low"][1]*9],
	"3-res-mid": [False, TILE_TYPES["zone-res-mid"][1]*9],
	"3-res-high": [False, TILE_TYPES["zone-res-high"][1]*9],
	"3-com-low": [False, TILE_TYPES["zone-com-low"][1]*9],
	"3-com-mid": [False, TILE_TYPES["zone-com-mid"][1]*9],
	"3-com-high": [False, TILE_TYPES["zone-com-high"][1]*9],
	"3-ind-low": [False, TILE_TYPES["zone-ind-low"][1]*9],
	"3-ind-mid": [False, TILE_TYPES["zone-ind-mid"][1]*9],
	"3-ind-high": [False, TILE_TYPES["zone-ind-high"][1]*9],

	"4-mixed-low": [False, TILE_TYPES["zone-mixed-low"][1]*16],
	"4-mixed-mid": [False, TILE_TYPES["zone-mixed-mid"][1]*16],
	"4-mixed-high": [False, TILE_TYPES["zone-mixed-high"][1]*16],
	"4-res-low": [False, TILE_TYPES["zone-res-low"][1]*16],
	"4-res-mid": [False, TILE_TYPES["zone-res-mid"][1]*16],
	"4-res-high": [False, TILE_TYPES["zone-res-high"][1]*16],
	"4-com-low": [False, TILE_TYPES["zone-com-low"][1]*16],
	"4-com-mid": [False, TILE_TYPES["zone-com-mid"][1]*16],
	"4-com-high": [False, TILE_TYPES["zone-com-high"][1]*16],
	"4-ind-low": [False, TILE_TYPES["zone-ind-low"][1]*16],
	"4-ind-mid": [False, TILE_TYPES["zone-ind-mid"][1]*16],
	"4-ind-high": [False, TILE_TYPES["zone-ind-high"][1]*16],

	"5-mixed-low": [False, TILE_TYPES["zone-mixed-low"][1]*25],
	"5-mixed-mid": [False, TILE_TYPES["zone-mixed-mid"][1]*25],
	"5-mixed-high": [False, TILE_TYPES["zone-mixed-high"][1]*25],
	"5-res-low": [False, TILE_TYPES["zone-res-low"][1]*25],
	"5-res-mid": [False, TILE_TYPES["zone-res-mid"][1]*25],
	"5-res-high": [False, TILE_TYPES["zone-res-high"][1]*25],
	"5-com-low": [False, TILE_TYPES["zone-com-low"][1]*25],
	"5-com-mid": [False, TILE_TYPES["zone-com-mid"][1]*25],
	"5-com-high": [False, TILE_TYPES["zone-com-high"][1]*25],
	"5-ind-low": [False, TILE_TYPES["zone-ind-low"][1]*25],
	"5-ind-mid": [False, TILE_TYPES["zone-ind-mid"][1]*25],
	"5-ind-high": [False, TILE_TYPES["zone-ind-high"][1]*25],

	"6-mixed-low": [False, TILE_TYPES["zone-mixed-low"][1]*36],
	"6-mixed-mid": [False, TILE_TYPES["zone-mixed-mid"][1]*36],
	"6-mixed-high": [False, TILE_TYPES["zone-mixed-high"][1]*36],
	"6-res-low": [False, TILE_TYPES["zone-res-low"][1]*36],
	"6-res-mid": [False, TILE_TYPES["zone-res-mid"][1]*36],
	"6-res-high": [False, TILE_TYPES["zone-res-high"][1]*36],
	"6-com-low": [False, TILE_TYPES["zone-com-low"][1]*36],
	"6-com-mid": [False, TILE_TYPES["zone-com-mid"][1]*36],
	"6-com-high": [False, TILE_TYPES["zone-com-high"][1]*36],
	"6-ind-low": [False, TILE_TYPES["zone-ind-low"][1]*36],
	"6-ind-mid": [False, TILE_TYPES["zone-ind-mid"][1]*36],
	"6-ind-high": [False, TILE_TYPES["zone-ind-high"][1]*36],

	"part": [False, 0]
}


IMAGE_LIST = [
	"none",
	*TILE_TYPES.keys(),
	*BUILDINGS_LIST.keys()
]
